services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: bookbuddy
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    restart: always
volumes:
  db: